print(" Welcome ")
print("I am a Calculator which give you Addition, Subtraction, Multiplication, Division Based on your Input")
print("Please Enter two Values")
m = int(input())
n = int(input())
print("Addition")
print(m+n)
print("Subtraction")
print(m-n)
print("Multiplication")
print(m*n)
print("Dividation")
print(m/n)
print("Thanks for using this calculator, Have a nice day!")
